name: GENESIS AI Brain
on:
  issues:
    types: [opened, edited]
  schedule:
    - cron: '0 1 * * *'  # 8 AM WIB

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python scripts/process_data.py
      - run: python scripts/ml_predict.py
      - run: python scripts/reflect.py
      - run: python scripts/sentiment.py
      - name: Respond
        run: echo "AI Brain processed"
