name: GENESIS Help
on:
  push:
    branches: [main]

jobs:
  help:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python scripts/help_engine.py
      - run: echo "Help commands updated"
