name: GENESIS Upgrade
on:
  push:
    branches: [main]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python auto-upgrade.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-upgrade GENESIS
